"""Regenerate brain/src/sops/index.yaml from the SOP files in this directory.

The output is hand-rendered (NOT yaml.dump) so the result is byte-stable
across PyYAML versions and operating systems — required for the drift-guard
test in tests/test_sop_index_drift.py.

CLI:
    python -m src.sops.build_index
"""

from __future__ import annotations

from pathlib import Path

from src.sops.loader import _sops_dir, load_all_sops

_HEADER = "# AUTO-GENERATED by python -m src.sops.build_index — do not hand-edit."


def build_index() -> str:
    """Render the current SOP catalog as a YAML string.

    Reads SOP files from disk via :func:`load_all_sops` (excludes
    ``index.yaml`` and ``disabled: true`` entries). Entries are sorted
    alphabetically by filename stem. Tags are rendered in source-file order
    as inline flow-style ``[t1, t2, t3]``.

    Returns:
        The full text that should be written to ``brain/src/sops/index.yaml``,
        ending with a single trailing newline.
    """
    sops = load_all_sops()  # already excludes disabled and index.yaml
    lines: list[str] = [_HEADER, "schema_version: 1", "sops:"]
    for name in sorted(sops):
        sop = sops[name]
        tags = ", ".join(sop["tags"])
        lines.append(f"  - name: {name}")
        lines.append(f"    file: {name}.yaml")
        lines.append(f"    description: {sop['description']}")
        lines.append(f"    tags: [{tags}]")
        lines.append(f"    yields: {sop['yields']}")
    return "\n".join(lines) + "\n"


def write_index() -> Path:
    """Write the generated catalog to ``brain/src/sops/index.yaml``.

    Returns:
        Absolute path to the written file.
    """
    path = _sops_dir() / "index.yaml"
    path.write_text(build_index(), encoding="utf-8")
    return path


if __name__ == "__main__":
    p = write_index()
    print(f"wrote {p}")
